name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.1.5"
      - run: lua tests/test_units.lua
      - run: lua tests/test_e2e.lua
